Feature/ex 18 mobile phone task exercise
KodzGS/JavaExercises pull request #5
Opened 2023-11-25 13:45 UTC by KodzGS

2023-12-11 15:04 UTC, owynowyn commented on src/main/java/Wall.java
> +public class Wall {
Same as before mate, I think you've branched off your Wall exercise work for this branch, might wanna hop on a call for 5 minutes to sort this out at some point 👍

2023-12-11 15:05 UTC, owynowyn commented on src/main/java/Contact.java
> +public class Contact {
Code is bang on bro, might just need an auto-format on this class, we can try and get something set up so you can do this a bit more intuitively too

2023-12-11 15:06 UTC, owynowyn commented on src/main/java/Contact.java
> +public class Contact {
When we can get on a call for 5

2023-12-11 15:06 UTC, owynowyn commented on src/main/java/MobilePhone.java
> +//test
Sneaky comment - remove

2023-12-11 15:08 UTC, owynowyn commented on src/main/java/MobilePhone.java
> +        return this.myContacts.indexOf(contact);
Small thing; probably dont need the `this` keyword here, doesn't change anything though, all looks good

2023-12-11 15:15 UTC, owynowyn commented on src/main/java/MobilePhone.java
> +        if (myContacts.contains(myContacts.indexOf(contact))) {
I dont think `myContacts.indexOf(contact)` will return what you expect here. The `myContacts.contain(Contact)` method, expects you to pass in a `Contact` object, but the `myContacts.indexOf(contact)` will return an int, so you will basically be calling `myContacts.contain(0)` for example. Which will probably result in an invalid argument exception as it expects `myContacts.contains(contact)`.
I would probably update this method to find the Contact within the list using the `String contact` parameter you have passed in, youll probably need a `for` loop for this. Give me a shout if you need some assistance with this or have a google

2023-12-11 15:18 UTC, owynowyn requested changes
Great work again mate, some adjustments to make to one of the methods but if we can get on a call this week to go through some of this then we should be in a really good place!

2023-12-15 15:48 UTC, KodzGS commented on src/main/java/MobilePhone.java
> +//test
removed

2023-12-15 16:33 UTC, merged